src/main/java/se/ifmo/web/model/DateBean.java
package se.ifmo.web.model;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

@Named(value = "date")
@ViewScoped
public class DateBean implements Serializable {
    private SimpleDateFormat simpleDateFormat;
    private Date date;

    public DateBean() {
        simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        date = new Date();
    }

    public String getCurrentDate() {
        return simpleDateFormat.format(date);
    }

    public void updateDate() {
        date = new Date();
    }
}

src/main/java/se/ifmo/web/model/Point.java
package se.ifmo.web.model;

import javax.persistence.*;

@Entity
@Table(name = "points")
public class Point {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "x_coordinate")
    private double xCoordinate;

    @Column(name = "y_coordinate")
    private double yCoordinate;

    @Column(name = "radius")
    private double radius;

    @Column(name = "inside_area")
    private boolean inside;

    public Point() { }

    public Point(double xCoordinate, double yCoordinate, double radius, boolean inside) {
        this.xCoordinate = xCoordinate;
        this.yCoordinate = yCoordinate;
        this.radius = radius;
        this.inside = inside;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getXCoordinate() {
        return xCoordinate;
    }

    public void setXCoordinate(double xCoordinate) {
        this.xCoordinate = xCoordinate;
    }

    public double getYCoordinate() {
        return yCoordinate;
    }

    public void setYCoordinate(double yCoordinate) {
        this.yCoordinate = yCoordinate;
    }

    public double getRadius() {
        return radius;
    }

    public void setRadius(double radius) {
        this.radius = radius;
    }

    public boolean isInside() {
        return inside;
    }

    public void setInside(boolean inside) {
        this.inside = inside;
    }
}

src/main/java/se/ifmo/web/controller/PointManagerBean.java
package se.ifmo.web.controller;

import se.ifmo.web.dao.PointDao;
import se.ifmo.web.model.Point;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named(value = "pointManager")
@SessionScoped
public class PointManagerBean implements Serializable {
    private Point point;
    private PointDao pointDao;

    public PointManagerBean() {
        point = new Point(0, 0, 1, false);
        pointDao = new PointDao();
    }

    public double getXCoordinate() {
        return point.getXCoordinate();
    }

    public void setXCoordinate(double xCoordinate) {
        point.setXCoordinate(xCoordinate);
    }

    public double getYCoordinate() {
        return point.getYCoordinate();
    }

    public void setYCoordinate(double yCoordinate) {
        point.setYCoordinate(yCoordinate);
    }

    public double getRadius() {
        return point.getRadius();
    }

    public void setRadius(double radius) {
        point.setRadius(radius);
    }

    public boolean isInside() {
        return point.isInside();
    }

    public void setInside(boolean inside) {
        point.setInside(inside);
    }

    public boolean checkAreas() {
        return AreaChecker.checkAreas(point.getXCoordinate(), point.getYCoordinate(), point.getRadius());
    }

    public void savePoint() {
        setInside(checkAreas());
        pointDao.save(point);
    }

    public void deleteAllPoints() {
        pointDao.deleteAllPoints();
    }

    public List<Point> getAllPoints() {
        return pointDao.getAllPoints();
    }
}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
>

<h:head>
    <title>Лаба 3</title>
    <h:outputStylesheet name="stylesMain.css" library="css"/>
    <h:outputStylesheet name="stylesResponse.css" library="css"/>
    <h:outputScript name="clock.js" library="js"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet"
          type="text/css"/>
</h:head>

<h:body style="background-color: #d4fff9 ">
    <header>
        P3232                      Федоров Никита(front)<br/>
        Вариант № 282305           Шахов кирилл(Back)<br/>


    </header>
    <br/>
    <div align="center" draggable="false" style="margin-top: 20%; ">
        <article class="mainRect animated zoomIn fast">
            <div align="center" draggable="false" >
                <canvas id="clock" title="clock" width="300px" height="300px" style="padding-top: 25px"/>
            </div>
            <br/>
            <h:form>
                <div align="center" draggable="false">
                    <p:linkButton outcome="main" action="check" id="check-button" value="В Нарнию"
                                  ajax="false" styleClass="buttonCheck" style="text-align: center"/>
                </div>
            </h:form>
        </article>
    </div>
</h:body>
</html>

src/main/webapp/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Главная страница</title>
    <h:outputStylesheet name="css/primeflex.css"/>
    <h:outputStylesheet name="css/custom.css"/>

</h:head>
<h:body>
    <header>
        <div class="p-grid p-justify-center">
            <div class="p-col-8 p-align-center" align="center">
                P3232                      Федоров Никита(front)<br/>
                Вариант № 282305           Шахов кирилл(Back)<br/>
            </div>
        </div>
    </header>

    <div class="p-grid p-justify-between">
        <div class="p-col-4 p-align-center" align="center">
            <canvas id="graph" width="300" height="300"/>
        </div>
        <div class="p-col-8 p-align-center">
            <p:dataTable id="points-table" value="#{pointManager.allPoints}" var="point" scrollable="true"
                         rowHover="true" emptyMessage="Данные отсутствуют" scrollHeight="200">
                <f:facet name="header">Список точек</f:facet>

                <p:column headerText="Координата X">
                    <h:outputText value="#{point.XCoordinate}"/>
                </p:column>

                <p:column headerText="Координата Y">
                    <h:outputText value="#{point.YCoordinate}"/>
                </p:column>

                <p:column headerText="Радиус">
                    <h:outputText value="#{point.radius}"/>
                </p:column>

                <p:column headerText="Попадание">
                    <h:outputText value="#{point.inside}">
                        <f:converter converterId="booleanConverter"/>
                    </h:outputText>
                </p:column>
            </p:dataTable>
        </div>
    </div>

    <h:form id="submit-form">
        <div class="p-grid p-justify-around">
            <div class="p-col-4 p-align-stretch" align="center">
                <p:outputLabel for="x-coordinate">Выберите координату X</p:outputLabel><br/>
                <h:outputText id="output-x" value="#{pointManager.XCoordinate}"/><br/>
                <h:inputHidden id="x-coordinate" value="#{pointManager.XCoordinate}">
                    <f:validator validatorId="xDataValidator"/>
                </h:inputHidden>
                <p:slider for="x-coordinate" minValue="-5" maxValue="5" step="1" display="output-x"
                          style="width: 200px; margin-top: 10px;"/>
                <p:message for="x-coordinate" style="margin-top: 7px"/>
            </div>

            <div class="p-col-4 p-align-center" align="center">
                <p:outputLabel for="y-coordinate">Введите координату Y</p:outputLabel><br/>
                <p:inputText id="y-coordinate" value="#{pointManager.YCoordinate}" style="margin-top: 10px;"
                             maxlength="15" placeholder="от -5 до 3">
                        <f:validator validatorId="yDataValidator"/>
                </p:inputText><br/>
                <p:message for="y-coordinate" display="default"/>
            </div>

            <div class="p-col-4 p-align-stretch" align="center">
                <p:outputLabel for="radius">Выберите радиус</p:outputLabel><br/>
                <h:outputText id="output-radius" value="#{pointManager.radius}"/><br/>
                <h:inputHidden id="radius" value="#{pointManager.radius}"/>
                <p:slider id="radius-slider" for="radius" minValue="1" maxValue="3" step="0.5" display="output-radius"
                          onSlide="handleSlide(event, ui)" style="width: 200px; margin-top: 10px;"/>
            </div>

            <div class="p-col-8" align="center">
                <p:linkButton style="width: 130px;" outcome="index" value="Вернуться"
                              icon="fa fa-fw fa-arrow-left"/>
                <p:commandButton style="width: 130px;" styleClass="submit-coordinate" type="submit" value="Проверить"
                                 action="#{pointManager.savePoint}" update="@form points-table ugly-function"
                                 icon="fa fa-fw fa-plus"/>
            </div>
        </div>
    </h:form>

    <h:form id="delete-form">
        <div class="p-grid p-justify-center">
            <div class="p-col-8" align="center">
        <p:commandButton style="width: 130px;" value="Очистить" action="#{pointManager.deleteAllPoints}"
                         type="submit" update="@form points-table ugly-function" icon="fa fa-fw fa-remove"/>
            </div>
        </div>
    </h:form>

    <h:outputScript name="js/graph-render.js"/>
    <h:outputScript name="js/click-submit.js"/>
    <h:outputScript name="js/scale-set.js"/>
    <h:outputScript name="js/click-render.js"/>
    <p:panel id="ugly-function" visible="false">
        <h:outputScript>
            function handleSlide(event, ui) {
                radius = ui.value;
                setPlaneScale(ui.value);
            <ui:repeat value="#{pointManager.allPoints}" var="point">
                drawClick("#{point.XCoordinate}", "#{point.YCoordinate}", "#{point.radius}", "#{point.inside}");
            </ui:repeat>
            }

            window.addEventListener('load', function(event) {
                setPlaneScale("${pointManager.radius}");
            <ui:repeat value="#{pointManager.allPoints}" var="point">
                drawClick("#{point.XCoordinate}", "#{point.YCoordinate}", "#{point.radius}", "#{point.inside}");
            </ui:repeat>
            });

            setPlaneScale(radius);
            <ui:repeat value="#{pointManager.allPoints}" var="point">
                drawClick("#{point.XCoordinate}", "#{point.YCoordinate}", "#{point.radius}", "#{point.inside}");
            </ui:repeat>
        </h:outputScript>
    </p:panel>

</h:body>
</html>